name: THIS IS GIT-HUB Actions CD
run-name: "${{ github.actor }} is learning GitHub Actions"
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
         fetch-depth: 2
      - name: finding changes
        id: changes
        shell: bash
        run: |
           changes=$(git diff HEAD^ HEAD --name-only) 
           count=$(for i in $changes; do echo $i; done | grep -e  '^script.*' > /dev/null ; echo $?)
           echo "count=$count" >> $GITHUB_OUTPUT
      - name: found changes in script.sh
        run: echo changes found in script.sh file
        if: ${{ steps.changes.outputs.count == '0' }}
         
              