name: learing-actions
run-name: ${{ github.actor }} RoboShop
on: [push]
jobs:
    job1:
      runs-on: ubuntu-latest
      env: 
        task: "git-actions"
      steps:
          - name: step1
            run: |
             echo "This is step-1"
            shell: bash
            if: ${{ env.task == 'actions'}}

          - name: step2
            run: |
             echo "This is step-2"
            shell: bash
            if: ${{ env.task == 'git-actions'}}    
            
              