name: learing-actions
run-name: ${{ github.actor }} RoboShop
on: [push]
jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
          - name: step1 
            run: echo "This is step1" && exit 1

          - name: step2
            if: ${{ failure() }}
            run: echo "This is step1"  