name: learing-actions
run-name: ${{ github.actor }} RoboShop
on: [push]
jobs:
    job1:
        env: 
          name: "job-chaitu"
        runs-on: ubuntu-latest 
        steps:
        - run: echo "This is env-${name}"