name: THIS IS GIT-HUB Actions
run-name: "${{ github.actor }} is learning GitHub Actions"
on: [push]

jobs:
  job1:
    runs-on: [self-hosted]
    steps:
      - name: This is step-1
        run: | 
           echo "new action runner"
  # job2: 
  #   runs-on: ubuntu-latest
  #   if: ${{ inputs.enternumber == '1' }}
  #   steps:
  #     - name: job2-step1
  #       run: echo "This is ${{ inputs.enternumber }}" 

  # job3: 
  #   runs-on: ubuntu-latest
  #   if: ${{ inputs.myboolean }}
  #   steps:
  #     - name: job2-step1
  #       run: echo "This is ${{ inputs.myboolean }}"                 
            
              