name: THIS IS GIT-HUB Actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: "Enter your name"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: This is step-1
        run: echo "This is Myname - ${{ inputs.name }}"  

            
            
              