name: THIS IS GIT-HUB Actions
run-name: "${{ github.actor }} is learning GitHub Actions"
on: 
  workflow_dispatch:
    inputs:
      name: 
        type: string
        description: "Enter the name:"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    #  - uses: actions/checkout@v4
      - name: This is step-1
        run: | 
           echo "new action runner"
           echo "${{ inputs.name }}  --  ${{ inputs.NAME }}" ; exit 1
              