name: learing-actions
run-name: ${{ github.actor }} RoboShop
on: [push]
jobs:
    job1:
      runs-on: ubuntu-latest
      env: 
        task: "git-actions"
      steps:
          - name: step1
            run: |
             echo "This is without mask -$task"
             echo "This is without mask -::add-mask::$task"
            
            
              