name: learing-actions
run-name: ${{ github.actor }} RoboShop
on: [push]
jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
          - name: step1
            run: echo "This is my ${name}"
            env:
              name: "step1-name-chaithanya"

          - name: step2
            run: echo "This is my ${name}"
            env:
              name: ${{ jobs.job1.steps[step1].name }}    