name: learing-actions
run-name: ${{ github.actor }} RoboShop
on: [push]
jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
          - name: step1
            run: |
             ls -l
            working-directory: /opt
              