name: learing-actions
run-name: ${{ github.actor }} RoboShop
on: [push]
jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
          - name: step1 
            run: echo "This is step1 - and ${GITHUB_ACTOR}"
            env:  
              GITHUB_ACTOR: ${{github.job}}