name: THIS IS GIT-HUB Actions
run-name: "${{ github.actor }} is learning GitHub Actions"
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        default: "chaithanya"
        description: "Enter your name"
      branches:
        type: choice
        description: "Select the branc"
        required: true
        default: "main"
        options:
          - "main"
          - "master"
          - "dev"  
      enternumber:
        type: number
        description: "Enter a number"
        required: true

      myboolean:
        type: boolean
        description: "My boolena"
        default: true  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: This is step-1
        run: |
          echo "This is Myname - ${{ inputs.name }}" 
          echo "This is branch - ${{ inputs.branches }}" 

  job2: 
    runs-on: ubuntu-latest
    if: ${{ inputs.enternumber == '1' }}
    steps:
      - name: job2-step1
        run: echo "This is ${{ inputs.enternumber }}" 

  job3: 
    runs-on: ubuntu-latest
    if: ${{ inputs.myboolean }}
    steps:
      - name: job2-step1
        run: echo "This is ${{ inputs.myboolean }}"                 
            
              