name: vault cli
run-name: "${{ github.actor }} is learning GitHub Actions"
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
    - name: set-up vault cli 
      uses: eLco/setup-vault@v1.0.3
    - name: vault-version
      run: vault --version  

    - name: update vault kv secrets
      run: vault kv patch -mount=test names name1="${{ github.actor }}"
      env: 
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        VAULT_ADDR: https://54.211.156.157:8200/
        VAULT_SKIP_VERIFY: true #


       